### ISSUE TITLE
1.20.1?

### ISSUE THREAD

**Issue by Pietr06** [JoakimThorsen/JoaCarpet#1]
![image](https://github.com/JoakimThorsen/JoaCarpet/assets/88508843/b0eb9096-a777-4688-86e7-23b6834a2aea)

**Comment by JoakimThorsen** [comment]
Perhaps 👀

**Comment by venaminecraft** [comment]
It's out @Pi3tro88.

https://modrinth.com/mod/joacarpet/version/uI9Tzall
