### ISSUE TITLE
crashed after update

### ISSUE THREAD

**Issue by acaciachan** [JoakimThorsen/JoaCarpet#2]
### Bug description

[crash-2024-07-11_20.47.28-client.txt](https://github.com/user-attachments/files/16177302/crash-2024-07-11_20.47.28-client.txt)

### Steps to reproduce

after recent update, it crashed

### Minecraft version

1.20.4

### TemplateMod version

joacarpet-mc1.20.x-v2.3

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by JoakimThorsen** [comment]
Cheers! It seems like the issue was a method moving in an earlier version than i expected (we love mojang making breaking changes in dot versions <3) but I hadn't caught it because I had been testing on 1.20.2. Fixed it now, will upload on modrinth shortly.
