### ISSUE TITLE
InsaneBehaviors (Sensible) crashes the game when container cart with an item gets broken by block.

### ISSUE THREAD

**Issue by DrakePHOSE** [JoakimThorsen/JoaCarpet#3]
### Bug description

When InsaneBehaviors (Sensible) is enabled, the game crashes when a hopper/chest minecart, with an item in it's inventory, get broken by a block, like a cactus or lava cauldron.

I'm not sure what "TemplateMod version" is referring too.
This is tested on fabric 0.15.11 - 1.21, and JoeCarpet 2.3

### Steps to reproduce

1. Turn on InsaneBehaviors (Sensible)
2. With an item in it's inventory, drive or push a hopper/chest cart into a cactus.

### Relevant logs

[crash-2024-07-18_15.27.35-server.txt](https://github.com/user-attachments/files/16288232/crash-2024-07-18_15.27.35-server.txt)

### Minecraft version

1.21

### TemplateMod version

2.3

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by DrakePHOSE** [comment]
Crash report was made when I had other mods and carpet rules. I have tested it with only carpet, fabric api, and joecarpet.
If you need, I can make a crash report with just those.

**Comment by JoakimThorsen** [comment]
No need, I've found out what the issue is already, just need to run a test and then compile the mods :)

**Comment by JoakimThorsen** [comment]
Fixed the issue, uploaded the artifacts to both github and modrinth now. Thanks for reporting!

(also, if you haven't already, look into the [insaneBehaviorsCartYeetingException](https://github.com/JoakimThorsen/JoaCarpet#insaneBehaviorsCartYeetingException))
